INSERT INTO ingrediente (nombre) VALUES ('Costillar');
INSERT INTO ingrediente (nombre) VALUES ('Ribeye');
INSERT INTO ingrediente (nombre) VALUES ('New york');
INSERT INTO ingrediente (nombre) VALUES ('T-bone');
INSERT INTO ingrediente (nombre) VALUES ('Filete');
INSERT INTO ingrediente (nombre) VALUES ('Porterhouse');
INSERT INTO ingrediente (nombre) VALUES ('Steak de filete');
INSERT INTO ingrediente (nombre) VALUES ('Steak de aguayon');
INSERT INTO ingrediente (nombre) VALUES ('Empuje');
INSERT INTO ingrediente (nombre) VALUES ('Falda');
INSERT INTO ingrediente (nombre) VALUES ('Pierna');
INSERT INTO ingrediente (nombre) VALUES ('Pulpa blanca');
INSERT INTO ingrediente (nombre) VALUES ('Cuete');
INSERT INTO ingrediente (nombre) VALUES ('Pulpa negra');
INSERT INTO ingrediente (nombre) VALUES ('Cadera');
INSERT INTO ingrediente (nombre) VALUES ('Bola');
INSERT INTO ingrediente (nombre) VALUES ('Arrachera');
INSERT INTO ingrediente (nombre) VALUES ('Pecho');
INSERT INTO ingrediente (nombre) VALUES ('Brazuelo');
INSERT INTO ingrediente (nombre) VALUES ('Paleta');
INSERT INTO ingrediente (nombre) VALUES ('Espaldilla');
INSERT INTO ingrediente (nombre) VALUES ('Corazon de diesmillo');
INSERT INTO ingrediente (nombre) VALUES ('Juil');
INSERT INTO ingrediente (nombre) VALUES ('Planchuela');
INSERT INTO ingrediente (nombre) VALUES ('Diezmillo');
INSERT INTO ingrediente (nombre) VALUES ('Suprema');
INSERT INTO ingrediente (nombre) VALUES ('Solomillo');
INSERT INTO ingrediente (nombre) VALUES ('Entraña');
INSERT INTO ingrediente (nombre) VALUES ('Presa');
INSERT INTO ingrediente (nombre) VALUES ('Entrecot');
INSERT INTO ingrediente (nombre) VALUES ('Rack');
INSERT INTO ingrediente (nombre) VALUES ('Tomahawk');
